In [46]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from config import GptConfig
from model import GPT

In [2]:
import os
os.environ.get('RANK', -1)

-1

In [7]:
torch.cuda.is_bf16_supported()

True

In [39]:
from datasets import load_dataset
import tiktoken
import numpy as np

repo_name = "Elriggs/openwebtext-100k"
ds = load_dataset(repo_name, split='train')
tokenizer = tiktoken.get_encoding('gpt2')
eot = tokenizer.eot_token
CONTEXT_LEN = 1024

def tokenize(doc):
    all_tokens = []
    input_tokens = []
    target = []
    token_lists = tokenizer.encode_ordinary_batch(doc['text'])
    for tokens in token_lists:
        all_tokens.extend([eot] + tokens)
        
    for i in range(0, len(all_tokens) - CONTEXT_LEN, CONTEXT_LEN):
        input_tokens.append(all_tokens[i : i + CONTEXT_LEN])
        target.append(all_tokens[i+1 :i + CONTEXT_LEN + 1])
        
    return {'input': input_tokens, "labels": target}

In [41]:
ds_map = ds.map(tokenize, batch_size=100000, batched=True, remove_columns=['text'])

Map:   0%|          | 0/100000 [00:00<?, ? examples/s]

In [36]:
10 == np.int16

False

In [53]:
print(torch.tensor(ds_map[-1]['input'])) 
torch.tensor(ds_map[-1]['labels']) 

tensor([   25,  1212,   318,  ..., 28840,   449, 11698])


tensor([ 1212,   318,  3190,  ...,   449, 11698,    45])

In [55]:
ds_map.save_to_disk('./pretrain_data/openwebtext_tokenized',)

Saving the dataset (0/4 shards):   0%|          | 0/110315 [00:00<?, ? examples/s]

In [8]:
config = GptConfig()

sample = torch.randint(1, 10, size=(1, 5)).to(config.device)
target = torch.randint(1, 10, size=(1, 5)).to(config.device)

gpt = GPT(config).to(config.device)

out = gpt(sample)

In [29]:
import inspect



In [4]:
out['logits'].dtype

torch.float32

In [3]:
from utils import load_checkpoint
load_checkpoint(model=gpt)

FileNotFoundError: [Errno 2] No such file or directory: 'checkpoints/ckpt.pt'

In [5]:
print(f"total parameters in the model")
total_params = 0
for params in gpt.parameters():
    total_params+=params.numel()
print(total_params)

total parameters in the model
124470865


In [ ]:
inputs = ['hai iam goint to'] * 5
gpt.generate(text=inputs, temperature=0.7, top_k=10)

["hai iam goint to-day;\nAnd, like a story of my joys,\nAnd bid her best array; and there lies\nAnd in their births: where is that's not\nIt is, but not the duke,\nIt shall be wary",
 "hai iam goint to her:\nShe was the loathed to her husband;\nShe was she born a shrew-day;\nAnd she, she, I'll play the church;\nAnd when she, there she, on me;\nI'll tell her",
 "hai iam goint to-day;\nAnd all the house of Lancaster hath been made\nAs well in the highness' the sun.\n\nNORFOLK:\nI thank God, the noble duke had me\nAnd he my daughter's hand.",
 'hai iam goint to-day.\n\nGLOUCESTER:\nWhy, then you would not call me;\nFor I was for you that I was stay.\n\nKING EDWARD IV:\nBrother, then, if I command,\nWhat',
 'hai iam goint to-day?\n\nHENRY BOLINGBROKE:\nIt is thy goodly time it.\n\nDUCHESS OF YORK:\nMyself I remember them well, nor my uncle;\nAnd yet my son']

In [ ]:
from dataset import get_data_loader

In [ ]:
import tiktoken
tokenizer = tiktoken.get_encoding('gpt2')
loader = get_data_loader(tokenizer)

In [ ]:
for x, y in loader:
    print(x, y)
    break

tensor([[   12,   448,   547,  ...,  1867,   338,   534],
        [   40,  2937,    25,  ...,   339,   318, 10657],
        [   25,   198, 39461,  ...,   307,   354,  2903],
        ...,
        [  561,   407,   423,  ...,  8322,  9399,    25],
        [   12,  1820,    12,  ...,    13,   198,   198],
        [  910,     0,  8805,  ...,   815,   307,  6190]]) tensor([[  448,   547,   286,  ...,   338,   534,  1438],
        [ 2937,    25,   198,  ...,   318, 10657,    26],
        [  198, 39461,    11,  ...,   354,  2903,   606],
        ...,
        [  407,   423,   340,  ...,  9399,    25,   198],
        [ 1820,    12,    67,  ...,   198,   198, 18973],
        [    0,  8805,   321,  ...,   307,  6190,    25]])


In [6]:
from datasets import load_dataset, load_from_disk
data = load_from_disk('pretrain_data\openwebtext_tokenized')

<>:2: SyntaxWarning: invalid escape sequence '\o'
<>:2: SyntaxWarning: invalid escape sequence '\o'
C:\Users\VICTUS\AppData\Local\Temp\ipykernel_3152\705726110.py:2: SyntaxWarning: invalid escape sequence '\o'
  data = load_from_disk('pretrain_data\openwebtext_tokenized')


In [ ]:
from torch.utils.data import DataLoader

{'input': [50256,
  13924,
  12,
  559,
  12,
  35784,
  11,
  25051,
  357,
  18474,
  8,
  1377,
  45591,
  4970,
  11,
  1319,
  44556,
  287,
  2356,
  290,
  44787,
  379,
  1204,
  11,
  7342,
  7519,
  290,
  20669,
  2513,
  1497,
  422,
  257,
  2214,
  4436,
  3217,
  1755,
  706,
  257,
  21402,
  3315,
  1074,
  23724,
  262,
  1989,
  11,
  2282,
  340,
  373,
  5213,
  546,
  2324,
  13,
  198,
  198,
  464,
  2551,
  1364,
  8100,
  5953,
  8366,
  34428,
  298,
  2986,
  33708,
  42095,
  355,
  262,
  691,
  6253,
  379,
  262,
  4436,
  284,
  651,
  262,
  3871,
  832,
  262,
  1755,
  13,
  198,
  198,
  18474,
  7317,
  2098,
  11,
  1912,
  319,
  10275,
  351,
  617,
  286,
  262,
  7519,
  11,
  326,
  262,
  1578,
  7973,
  6149,
  262,
  21402,
  3274,
  22225,
  290,
  7929,
  4816,
  284,
  36316,
  13,
  2102,
  11,
  21402,
  5953,
  36831,
  2269,
  861,
  402,
  2926,
  82,
  11,
  257,
  6253,
  508,
  373,
  379,
  262,
  4436,
  351,
  3126,
  21402,
